site_name: Covid
nav:
  - Getting Started: index.md
  - Install: install.md
  - John Hopkins University API: john_hopkins.md
  - Worldometers.info (New): worldometers.md
theme:
  name: "material"
  palette:
    primary: "red"
markdown_extensions:
  - codehilite
