version: 2.1 # use CircleCI 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  poetry: frameio/poetry@0.13.2

jobs:
  build:
    working_directory: ~/covid
    docker:
      - image: circleci/python:3.7.5

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: Run Tests
          command: |
            pipenv run coverage run -m pytest tests.py
            pipenv run coverage report
            pipenv run coverage xml
      - store_artifacts:
          path: coverage.xml
      - codecov/upload:
          file: coverage.xml
          flags: backend
